### ISSUE TITLE
 Application error when trying to access APIs

### ISSUE THREAD

**Issue by shashankmehra** [fake-news-detector/fake-news-detector#29]
Your service endpoints [https://api.fakenewsdetector.org/](https://api.fakenewsdetector.org/) and [https://robinho.fakenewsdetector.org/](https://robinho.fakenewsdetector.org/) seem to be throwing "Application error" on heroku. As a result the form on [https://fakenewsdetector.org/en](https://fakenewsdetector.org/en) and the telegram bot are both not working.

**Comment by mochadwi** [comment]
https://robinho.fakenewsdetector.org/ @rogeriochaves seem to be 404 not found

**Comment by rogeriochaves** [comment]
@mochadwi it's fine that it is 404, it's not supposed to be accessed directly, the endpoints are working though, such as: https://robinho.fakenewsdetector.org/predict?title=foo&content=bar&url=http://example.org

If you want to play around with it you can download the postman collection and use postman to play with the API endpoints: https://github.com/fake-news-detector/fake-news-detector/tree/master/robinho/dev
